# Generated by Django 2.0 on 2018-02-05 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mcbiclustweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='gene_expr_mat',
            field=models.FileField(upload_to='analyses/'),
        ),
    ]
