# Generated by Django 2.0 on 2018-02-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbiclustweb', '0004_auto_20180220_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
