# Generated by Django 2.0 on 2018-02-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbiclustweb', '0005_auto_20180220_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
