# Generated by Django 2.0 on 2018-03-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbiclustweb', '0007_auto_20180226_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='char_ok',
            field=models.BooleanField(default=True),
        ),
    ]
