# Generated by Django 2.0 on 2018-04-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcbiclustweb', '0008_analysis_char_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biclusters',
            name='analysis',
        ),
        migrations.DeleteModel(
            name='Biclusters',
        ),
    ]
